services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa5S5w0rd2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Pa5S5w0rd2021", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssql-data:/var/opt/mssql

  productsmanangement:
    build:
      context: .
      dockerfile: productsManangement/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      ms-sql-server:
        condition: service_healthy

volumes:
  mssql-data:
