services:
  ms-sql-server:
    image: ://microsoft.com
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  productsmanangement:
    build:
      context: .
      dockerfile: productsManangement/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - ms-sql-server
